language: python
python:
  - "3.5"

before_install:
  - "pip install -r requirements.txt"
script:
  - coverage run --omit="*virtualenv*","env*","library/migrations/*" manage.py test
branches:
  only:
  - develop

after_success:
    - coveralls